<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAP_OUT" Id="{c5b05d38-318e-436f-a847-8491a50e7418}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAP_OUT
VAR


  uTransportState     : U_XTS_TRANSPORT_STATE;
  uStationState       : U_STATION_STATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[


  memcpy(ADR(uTransportState),  ADR(GVL_XTS.XtsTransportState),   SIZEOF(ST_XTS_TRANSPORT_STATE));
  memcpy(ADR(uStationState),    ADR(GVL_XTS.StationState),        SIZEOF(uStationState));


]]></ST>
    </Implementation>
    <LineIds Name="MAP_OUT">
      <LineId Id="10" Count="6" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>